version: '3.8'

services:
  database:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    restart: always
  backend:
    build: ./django_backend
    command: >
      sh -c "python manage.py makemigrations backend &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_backend:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - database
  frontend:
    build: ./vue_frontend
    command: >
      sh -c "npm run serve"
    volumes:
      - ./vue_frontend/public:/usr/src/app/public
      - ./vue_frontend/src:/usr/src/app/src
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  postgres-data:
